const HIT_SEND_CARDS = [
  {
    id: "send-verified-client-draft",
    to: "Maya Torres, client",
    subject: "Draft Complaint",
    message: "Attached is the draft complaint we discussed. Please review it and flag anything inaccurate.",
    detail: "You confirmed Maya's address and opened the file to verify that it is the correct draft.",
    attachment: "Torres_Draft_Complaint.pdf",
    answer: "send",
    feedback: "The recipient and attachment were both checked. This email is ready to send.",
    category: "verified attachment"
  },
  {
    id: "send-deposition-dates",
    to: "Opposing counsel",
    subject: "Available deposition dates",
    message: "We are available October 8, 10, or 14. Please let us know which date works for your team.",
    detail: "You checked the attorney's calendar and confirmed the recipient before drafting this reply.",
    attachment: "",
    answer: "send",
    feedback: "The dates and recipient are confirmed, and the message is clear and professional.",
    category: "scheduling"
  },
  {
    id: "send-public-order",
    to: "Client",
    subject: "Requested public order",
    message: "Attached is the publicly filed order you requested.",
    detail: "You confirmed the client's address and the attachment, then used the approved work system.",
    attachment: "Filed_Order.pdf",
    answer: "send",
    feedback: "The recipient, attachment, and sending method have all been checked.",
    category: "public document"
  },
  {
    id: "send-client-receipt",
    to: "Client",
    subject: "Documents received",
    message: "Thank you. I received the documents you sent this morning.",
    detail: "You are simply confirming receipt and have checked the recipient.",
    attachment: "",
    answer: "send",
    feedback: "A brief, accurate acknowledgment lets the client know the documents arrived.",
    category: "client acknowledgment"
  },
  {
    id: "send-filing-update",
    to: "Supervising attorney",
    subject: "Filing completed",
    message: "The motion was filed at 2:14 p.m. The filing confirmation is saved in the case folder.",
    detail: "You checked the filing receipt before writing this factual internal update.",
    attachment: "",
    answer: "send",
    feedback: "The update is factual, concise, and based on a checked filing receipt.",
    category: "internal update"
  },
  {
    id: "send-corrected-attachment",
    to: "Client",
    subject: "Revised draft",
    message: "Attached is the revised draft for your review.",
    detail: "Before sending, you replaced the wrong draft, opened the new file, and confirmed the recipient.",
    attachment: "Revised_Draft.pdf",
    answer: "send",
    feedback: "You corrected the attachment and verified both the file and recipient.",
    category: "corrected attachment"
  },
  {
    id: "send-meeting-confirmation",
    to: "Client",
    subject: "Meeting confirmation",
    message: "This confirms our meeting tomorrow at 10:30 a.m. at the firm's office.",
    detail: "You checked the calendar and the client's address before sending.",
    attachment: "",
    answer: "send",
    feedback: "The time and recipient are confirmed, so the meeting reminder is ready.",
    category: "meeting confirmation"
  },
  {
    id: "send-clear-subject",
    to: "Client",
    subject: "Meeting Confirmation - October 12",
    message: "Our October 12 meeting is confirmed for 3:00 p.m.",
    detail: "The subject accurately describes this routine scheduling message.",
    attachment: "",
    answer: "send",
    feedback: "The clear subject line helps the recipient understand and find the message.",
    category: "subject line"
  },
  {
    id: "send-calm-response",
    to: "Opposing counsel",
    subject: "RE: Document request",
    message: "We received your request and will respond by Thursday.",
    detail: "After receiving a sharp email, you waited, reread your draft, and removed emotional language.",
    attachment: "",
    answer: "send",
    feedback: "The final response is short, factual, and professional.",
    category: "professional tone"
  },
  {
    id: "send-requested-filing",
    to: "Another law office",
    subject: "Filed notice",
    message: "Attached is the filed notice requested by your office.",
    detail: "Your attorney asked you to send it, and you verified the recipient and attachment.",
    attachment: "Filed_Notice.pdf",
    answer: "send",
    feedback: "The request, recipient, and attachment are all confirmed.",
    category: "requested document"
  },
  {
    id: "send-internal-question",
    to: "Case team member",
    subject: "Status of routine filing",
    message: "Has today's routine filing been completed? Please let me know when the receipt is available.",
    detail: "You are using the firm's approved email system and selected the correct team member.",
    attachment: "",
    answer: "send",
    feedback: "This is a clear internal question sent through the approved system.",
    category: "internal communication"
  },
  {
    id: "send-autocomplete-checked",
    to: "Lena Ortiz, client",
    subject: "Appointment time",
    message: "Your appointment is confirmed for Tuesday at 9:00 a.m.",
    detail: "Autocomplete showed two people named Lena. You checked the file and selected the client's confirmed address.",
    attachment: "",
    answer: "send",
    feedback: "You resolved the autocomplete ambiguity before sending.",
    category: "autocomplete"
  },
  {
    id: "send-court-receipt-update",
    to: "Supervising attorney",
    subject: "Court submission received",
    message: "The court's online system shows that today's submission was received.",
    detail: "You checked the online confirmation before preparing this update.",
    attachment: "",
    answer: "send",
    feedback: "The update accurately reports information you verified.",
    category: "confirming facts"
  },
  {
    id: "send-vendor-invoice",
    to: "Office manager",
    subject: "Copy service invoice",
    message: "Attached is the invoice from the copy service for approval.",
    detail: "You matched the invoice to the completed job and verified the office manager's address.",
    attachment: "Copy_Service_Invoice.pdf",
    answer: "send",
    feedback: "The invoice and recipient have been checked, so the message is ready.",
    category: "vendor communication"
  },
  {
    id: "send-expert-materials",
    to: "Retained expert",
    subject: "Materials for Friday's meeting",
    message: "Attached are the three documents the attorney asked me to send for Friday's meeting.",
    detail: "You confirmed the expert's address and opened each of the three approved files.",
    attachment: "Meeting_Materials.zip",
    answer: "send",
    feedback: "The intended files and recipient were confirmed before sending.",
    category: "expert communication"
  },
  {
    id: "send-witness-directions",
    to: "Witness",
    subject: "Directions for tomorrow's meeting",
    message: "Our office is on the fourth floor. Please check in with reception when you arrive at 1:00 p.m.",
    detail: "You checked the appointment time and the witness's email address.",
    attachment: "",
    answer: "send",
    feedback: "The message gives checked, practical details to the intended recipient.",
    category: "witness logistics"
  },
  {
    id: "send-approved-bcc",
    to: "Undisclosed recipients",
    subject: "Office closure notice",
    message: "Our office will close Friday at 2:00 p.m. and reopen Monday morning.",
    detail: "Your office approved the notice, and the unrelated recipients are placed in BCC.",
    attachment: "",
    answer: "send",
    feedback: "The approved notice protects recipients' addresses by using BCC.",
    category: "bcc"
  },
  {
    id: "send-proofread-name",
    to: "Elena Rivera, client",
    subject: "Next appointment",
    message: "Dear Ms. Rivera, your next appointment is scheduled for November 6.",
    detail: "You proofread the greeting and confirmed both the name and date.",
    attachment: "",
    answer: "send",
    feedback: "The name and appointment date were checked before sending.",
    category: "proofreading"
  },
  {
    id: "send-neutral-subject",
    to: "Client",
    subject: "Case update",
    message: "I am writing with the routine update we discussed by phone.",
    detail: "You used a neutral subject and the firm's approved system for this confidential message.",
    attachment: "",
    answer: "send",
    feedback: "The neutral subject avoids putting unnecessary sensitive detail in the inbox view.",
    category: "confidential subject line"
  },
  {
    id: "send-needed-reply-all",
    to: "All meeting attendees",
    subject: "RE: New meeting room",
    message: "I received the room change and will meet everyone in Room 410.",
    detail: "The organizer asked every attendee to Reply All so the group would know who received the change.",
    attachment: "",
    answer: "send",
    feedback: "Everyone needs this confirmation, and the organizer specifically requested Reply All.",
    category: "reply all"
  },
  {
    id: "send-public-link",
    to: "Coworker",
    subject: "Public court calendar",
    message: "Here is the public court calendar link you requested: courts.example/calendar",
    detail: "You opened the link to confirm that it works and points to the public calendar.",
    attachment: "",
    answer: "send",
    feedback: "The requested public link was checked and is ready to share.",
    category: "public information"
  },
  {
    id: "send-client-arrival-update",
    to: "Client",
    subject: "Arrival time for Monday",
    message: "Please arrive at our office at 8:45 a.m. on Monday so we can meet before the appointment.",
    detail: "The attorney confirmed the arrival time, and you checked the client's address.",
    attachment: "",
    answer: "send",
    feedback: "The instruction and recipient have been confirmed.",
    category: "client communication"
  },
  {
    id: "send-approved-document-request",
    to: "Client",
    subject: "Documents for our meeting",
    message: "Please bring your March pay stubs and the signed offer letter to our Thursday meeting.",
    detail: "The attorney approved this list, and you confirmed the meeting date and recipient.",
    attachment: "",
    answer: "send",
    feedback: "The request is specific, approved, and sent to the confirmed client.",
    category: "client document request"
  },
  {
    id: "hold-wrong-autocomplete",
    to: "Maya Thompson?",
    subject: "Your case documents",
    message: "Here are the confidential documents you requested.",
    detail: "Autocomplete selected an unfamiliar person with a similar name.",
    attachment: "Client_Case_Documents.pdf",
    answer: "dont-send",
    feedback: "Check the address first. Autocomplete selected someone you do not recognize.",
    category: "wrong recipient"
  },
  {
    id: "hold-missing-attachment",
    to: "Supervising attorney",
    subject: "Witness interview notes",
    message: "Please see attached for the interview notes from this morning.",
    detail: "No file is attached.",
    attachment: "",
    answer: "dont-send",
    feedback: "The message promises an attachment, but none is there. Attach and verify the file first.",
    category: "missing attachment"
  },
  {
    id: "hold-angry-response",
    to: "Opposing counsel",
    subject: "RE: Your ridiculous demand",
    message: "THIS IS A COMPLETE WASTE OF EVERYONE'S TIME. READ THE RULES BEFORE EMAILING ME AGAIN.",
    detail: "You drafted this immediately after receiving a rude message.",
    attachment: "",
    answer: "dont-send",
    feedback: "Pause before responding while angry. Rewrite the message in a calm, professional tone.",
    category: "angry response"
  },
  {
    id: "hold-forwarded-comments",
    to: "Client",
    subject: "Fwd: Status update",
    message: "Forwarding the update below for your review.",
    detail: "The forwarded chain includes internal comments that were not intended for the client.",
    attachment: "",
    answer: "dont-send",
    feedback: "Review the entire chain before forwarding. Remove internal material that was not intended for the recipient.",
    category: "forwarding"
  },
  {
    id: "hold-unneeded-reply-all",
    to: "All 14 recipients",
    subject: "RE: Conference room",
    message: "Room 3B works for me. Thanks!",
    detail: "Only the office manager needs your answer, but you selected Reply All.",
    attachment: "",
    answer: "dont-send",
    feedback: "Only one person needs the answer. Reply to that person instead of adding unnecessary email to everyone's inbox.",
    category: "reply all"
  },
  {
    id: "hold-visible-client-addresses",
    to: "Several unrelated clients",
    subject: "Office closure notice",
    message: "Our office will be closed Friday afternoon.",
    detail: "Every client's address is visible in the CC field.",
    attachment: "",
    answer: "dont-send",
    feedback: "Do not expose unrelated clients' addresses. Use the office's approved bulk-email method.",
    category: "cc"
  },
  {
    id: "hold-unchecked-final",
    to: "Client",
    subject: "Document update",
    message: "Attached is the final version.",
    detail: "You have not opened the file to confirm what it contains.",
    attachment: "Complaint_FINAL_v7_REALFINAL.pdf",
    answer: "dont-send",
    feedback: "Open the attachment before sending. A filename does not guarantee that it is the correct version.",
    category: "unchecked attachment"
  },
  {
    id: "hold-email-record",
    to: "Coworker",
    subject: "Case update",
    message: "Maybe if we ignore this long enough, they'll give up.",
    detail: "You are about to send this in a routine case email.",
    attachment: "",
    answer: "dont-send",
    feedback: "Email can later be read by people beyond the original recipient. Keep case communications factual and professional.",
    category: "email as a record"
  },
  {
    id: "hold-sarcastic-update",
    to: "Client",
    subject: "Case update",
    message: "Opposing counsel's argument is honestly embarrassing.",
    detail: "You included this line in a routine case update to the client.",
    attachment: "",
    answer: "dont-send",
    feedback: "Keep case updates factual and professional. Email can be forwarded, preserved, or read later by someone else.",
    category: "sarcasm"
  },
  {
    id: "hold-personal-account",
    to: "Client",
    subject: "Case summary",
    message: "Attached is the confidential case summary you requested.",
    detail: "You are using a personal email account even though your office requires its approved work system.",
    attachment: "Case_Summary.pdf",
    answer: "dont-send",
    feedback: "Use the approved work system for confidential legal-work messages.",
    category: "approved work system"
  },
  {
    id: "hold-wrong-version",
    to: "Supervising attorney",
    subject: "Draft for review",
    message: "Attached is the revised draft.",
    detail: "Three different drafts are in the folder, and you have not checked which one is attached.",
    attachment: "draft.pdf",
    answer: "dont-send",
    feedback: "Confirm which version is attached before sending it.",
    category: "version control"
  },
  {
    id: "hold-uncertain-address",
    to: "r.morgan@example.com?",
    subject: "Appointment details",
    message: "Your appointment is scheduled for Wednesday at 11:00 a.m.",
    detail: "You are not sure whether this address belongs to the intended client.",
    attachment: "",
    answer: "dont-send",
    feedback: "Confirm that the address belongs to the intended client before sending.",
    category: "recipient"
  },
  {
    id: "hold-revealing-subject",
    to: "Client",
    subject: "YOUR TERMINATION LAWSUIT AGAINST YOUR BOSS",
    message: "I am writing with the routine update we discussed.",
    detail: "The subject appears in notifications and reveals more sensitive detail than this message needs.",
    attachment: "",
    answer: "dont-send",
    feedback: "Use a neutral subject line that does not expose unnecessary sensitive information.",
    category: "subject line"
  },
  {
    id: "hold-unverified-cancellation",
    to: "Client",
    subject: "Hearing cancelled",
    message: "The hearing has been cancelled, so you do not need to attend.",
    detail: "You heard this from a coworker but have not checked the court notice or confirmed it with the attorney.",
    attachment: "",
    answer: "dont-send",
    feedback: "Confirm the cancellation before telling the client not to attend.",
    category: "unverified fact"
  },
  {
    id: "hold-folder-export",
    to: "Vendor",
    subject: "Requested invoice",
    message: "Attached is the invoice you requested.",
    detail: "Instead of the one invoice, the attachment is an export of the entire case folder.",
    attachment: "Case_Folder_Export.zip",
    answer: "dont-send",
    feedback: "Attach only the requested invoice. The folder export contains unrelated material.",
    category: "accidental oversharing"
  },
  {
    id: "hold-unreviewed-chain",
    to: "Expert",
    subject: "Fwd: Background information",
    message: "The newest message has the background you requested.",
    detail: "You are forwarding a long chain without checking the earlier messages below it.",
    attachment: "",
    answer: "dont-send",
    feedback: "Review the full chain before forwarding so you know exactly what the recipient will receive.",
    category: "email chain"
  },
  {
    id: "hold-placeholder",
    to: "Client",
    subject: "Meeting follow-up",
    message: "Dear [INSERT CLIENT NAME], thank you for meeting with us today.",
    detail: "The placeholder is still in the draft.",
    attachment: "",
    answer: "dont-send",
    feedback: "Replace the placeholder and proofread the message before sending.",
    category: "proofreading"
  },
  {
    id: "hold-wrong-name",
    to: "Elena Rivera, client",
    subject: "Next appointment",
    message: "Dear Mr. Johnson, your next appointment is scheduled for November 6.",
    detail: "The greeting uses a different client's name.",
    attachment: "",
    answer: "dont-send",
    feedback: "Correct the greeting before sending. The name does not match the recipient.",
    category: "wrong name"
  },
  {
    id: "hold-mirrored-anger",
    to: "Client",
    subject: "RE: Why is this taking so long?",
    message: "You're right. Everyone involved has made a complete mess of this.",
    detail: "You drafted this immediately after the client sent an angry message.",
    attachment: "",
    answer: "dont-send",
    feedback: "Do not mirror the client's anger. Respond calmly and address the issue with accurate information.",
    category: "client communication"
  },
  {
    id: "hold-scheduling-overshare",
    to: "Another law office",
    subject: "Available dates",
    message: "Tuesday will not work because our client is receiving private medical treatment that morning. Thursday is available.",
    detail: "The other office only asked which dates are available.",
    attachment: "",
    answer: "dont-send",
    feedback: "Give the available date without adding private personal details that the recipient did not need.",
    category: "oversharing"
  },
  {
    id: "hold-sensitive-subject",
    to: "Coworker",
    subject: "Jordan Lee's Social Security Number",
    message: "I have the information you requested.",
    detail: "The sensitive detail does not need to appear in the subject line.",
    attachment: "",
    answer: "dont-send",
    feedback: "Remove sensitive information from the subject line and use a neutral description.",
    category: "confidential subject line"
  },
  {
    id: "hold-unclear-file",
    to: "Client",
    subject: "Requested document",
    message: "Attached is the document you requested.",
    detail: "The folder contains scan1.pdf, scan2.pdf, and final.pdf, and you have not opened the attached file.",
    attachment: "final.pdf",
    answer: "dont-send",
    feedback: "Open the attachment before sending. The filename does not show which document it contains.",
    category: "unclear attachment"
  },
  {
    id: "hold-wrong-attachment",
    to: "Client",
    subject: "Requested public order",
    message: "Attached is the public order you requested.",
    detail: "The attached file is a different client's settlement summary, not the public order.",
    attachment: "Settlement_Summary.pdf",
    answer: "dont-send",
    feedback: "Remove the wrong file and attach the requested public order before sending.",
    category: "wrong attachment"
  }
];
